### ISSUE TITLE
Problemas con el hover

### ISSUE THREAD

**Issue by Blxsky** [Blxsky/Proyectos#1]
No sé si mi app (Android) no me está reconociendo el hover en los links ó estoy haciendo algo mal.

**Comment by Blxsky** [comment]
![Screenshot_2023-07-07-22-34-11-338_com.teejay.trebedit.jpg](https://github.com/Blxsky/Proyectos/assets/134626353/26644ca2-a276-4132-87f8-4b09b28dfc35)

![Screenshot_2023-07-07-22-33-51-581_com.teejay.trebedit.jpg](https://github.com/Blxsky/Proyectos/assets/134626353/3e8872e0-1518-4a48-8ca8-d26df228bc80)

![Screenshot_2023-07-07-22-34-08-433_com.teejay.trebedit.jpg](https://github.com/Blxsky/Proyectos/assets/134626353/607c7c6d-2589-4770-8917-53f58b7a2e4a)

**Comment by Blxsky** [comment]
Pd. Cambie el hover por active para ver si ese era el problema, pero con ninguno me funcionó

**Comment by abrahamalanya** [comment]
Al parecer ya se ha solucionado el error, podrías cerrar el issue 👍🏼 
Puedes compartir la solución para que lo tengas en cuenta en el historial.

**Comment by Blxsky** [comment]
El problema no era nada de lo que pensaba, tenía un doble # en el color y eso evitaba la animación de hover.
